### ISSUE TITLE
AUR package disappeared.

### ISSUE THREAD

**Issue by tomoki** [passcod/twd#5]
Hi.

I noticed that I cannot find the twd package for Arch Linux on AUR.
I confirmed it from a terminal, and web browsers.

```
$ yaourt -S twd
error: target not found: twd
```

https://aur.archlinux.org/packages/twd

I think it is because twd package was not updated for AUR 4.
We need some work to migrate it.
https://wiki.archlinux.org/index.php/Arch_User_Repository#AUR_4

**Comment by passcod** [comment]
Unfortunate. I'll see what I can do, although it might not be until this weekend.

**Comment by passcod** [comment]
I'm not using twd anymore (since quite a while). If someone wants to repackage it for AUR, that'd be great, but I'm probably not going to.
